services:
  postgres:
    image: postgres:15
    container_name: stockviewer-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER:-user}", "-d", "${DB_NAME:-stockviewer}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  spring:
    build:
      context: ./stock_api_service
      dockerfile: Dockerfile
    container_name: stockviewer-spring
    restart: on-failure
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"

  go:
    build:
      context: ./stock_scheduler_service
      dockerfile: Dockerfile
    container_name: stockviewer-go
    restart: on-failure
    volumes:
      - .env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  kafka:
    image: bitnami/kafka:3.6.0
    container_name: stockviewer-kafka
    restart: always
    env_file:
      - .env
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      retries: 10

volumes:
  pgdata: